[package]
  cjc-version = "1.1.0"
  name = "rt"
  organization = ""
  description = "Cangjie runtime replacement modules"
  version = "0.1.0"
  target-dir = "target"
  script-dir = ""
  src-dir = "src/rt"
  output-type = "static"
  compile-option = "--int-overflow wrapping"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
